export const colors = {
    primary: '#4A90E2',
    primaryLight: '#7FB5FF',
    primaryDark: '#2A6BC2',
    secondary: '#9D7FE6',
    secondaryLight: '#BCA4F6',
    secondaryDark: '#7D5FC6',
    success: '#4CD964',
    warning: '#FFCC00',
    danger: '#FF3B30',
    info: '#5AC8FA',
    background: '#F9F9FB',
    card: '#FFFFFF',
    text: '#1C1C1E',
    textSecondary: '#8E8E93',
    border: '#E5E5EA',
    borderLight: '#F2F2F7',
    overlay: 'rgba(0, 0, 0, 0.5)',
  };